apiVersion: example.com/v1
kind: JsonServer
metadata:
  labels:
    app.kubernetes.io/name: json-scheduler
    app.kubernetes.io/managed-by: kustomize
  name: jsonserver-sample
spec:
  # TODO(user): Add fields here
